### ISSUE TITLE
Customize Download broken ? - TypeError: float() argument must be a string or a real number, not 'NoneType'

### ISSUE THREAD

**Issue by ghost** [aliencaocao/ytdlp-gui#3]
trying to download a song from youtube, fresh download of the latest release on github

pasting the URL in the field and click customize downloads, then this error appear
download video and download audio works fine !

![image](https://github.com/aliencaocao/ytdlp-gui/assets/97499891/46b33cd0-05cf-4160-a670-e0e46d32e932)

**Comment by aliencaocao** [comment]
Can you try building from the latest commit? I fixed a possible cause of this but havent release a new update yet as im still working on other features

**Comment by ghost** [comment]
trying to build currently but having issue with the instructions you provided (i'm also quite rusty, havent played around with code in almost a year). if you have a mean to contact me in real-time i will assist as best as i can :)

`pip install -U -r ./requirements.txt` (Works)

`create-version-file version.yml --outfile version.txt` (Fails)
![image](https://github.com/aliencaocao/ytdlp-gui/assets/97499891/8724cc13-ab95-412e-9495-18fa04f48a8d)

`pyinstaller --log-level DEBUG -F -i icon.ico --version-file=version.txt --add-data "icon.png;." --add-data "ffmpeg.exe;." --add-data "ffprobe.exe;." --distpath ./ --clean --noconfirm "yt-dlp-gui.py"` (Fails)
![image](https://github.com/aliencaocao/ytdlp-gui/assets/97499891/5c041c4b-48c6-427c-8a26-278813526575)

**Comment by palindrome-wow** [comment]
yea thats my bad, forgot to update the README.
you need to first `pip install pyinstaller-versionfile` then `create-version-file version.yml --outfile version.txt`

**Comment by aliencaocao** [comment]
yea thats my bad, forgot to update the README.
you need to first pip install pyinstaller-versionfile then create-version-file version.yml --outfile version.txt

**Comment by aliencaocao** [comment]
Wait I just took a look again. You ran the commands in the wrong place. You should run this in the system cmd, not python shell. You were running `create-version-file version.yml --outfile version.txt` in python shell. I will update the doc to specify this.

**Comment by ghost** [comment]
i had actually performed a side-hustle to make this work.
first downloading a file with the proposed options works, then custom downloads that same file once again.
i might need to reinstall this from scratch to see if what you suggested truly was the issue.

sorry took a while, been busy with life and work !
